# -*- mode: python ; coding: utf-8 -*-


block_cipher = None


a = Analysis(
    ['timeflux_coherence_circle.py'],
    pathex=[],
    binaries=[("./env_timeflux_coherence_circle/lib/python3.9/site-packages/_libsuinput.cpython-39-x86_64-linux-gnu.so", "."),
    ("./env_timeflux_coherence_circle/lib/python3.9/site-packages/brainflow/lib/", "brainflow/lib"),
    ("./env_timeflux_coherence_circle/lib/python3.9/site-packages/pylsl/lib/", "pylsl/lib"),
    ("./env_timeflux_coherence_circle/lib/python3.9/site-packages/pyzmq.libs/", "pyzmq.libs"),
    ("./env_timeflux_coherence_circle/lib/python3.9/site-packages/tables/", "tables"),
    ("./env_timeflux_coherence_circle/lib/python3.9/site-packages/opencv_python.libs/", "opencv_python.libs"),
    ],
    datas=[("./env_timeflux_coherence_circle/lib/python3.9/site-packages/mne", "mne"),
    ("./env_timeflux_coherence_circle/lib/python3.9/site-packages/timeflux", "timeflux"),
    ("./env_timeflux_coherence_circle/lib/python3.9/site-packages/timeflux_neurofeedback_inverse_gamepad", "timeflux_neurofeedback_inverse_gamepad"),
    ("./env_timeflux_coherence_circle/lib/python3.9/site-packages/zmq", "zmq"),
    ("./env_timeflux_coherence_circle/lib/python3.9/site-packages/pythonosc", "pythonosc"),
    ("./env_timeflux_coherence_circle/lib/python3.9/site-packages/pyedflib", "pyedflib"),
    ("./env_timeflux_coherence_circle/lib/python3.9/site-packages/pylsl", "pylsl"),
    ("./env_timeflux_coherence_circle/lib/python3.9/site-packages/evdev", "evdev"),
    ("./env_timeflux_coherence_circle/lib/python3.9/site-packages/xarray", "xarray"),
    ("./env_timeflux_coherence_circle/lib/python3.9/site-packages/timeflux_ui", "timeflux_ui"),
    ("./env_timeflux_coherence_circle/lib/python3.9/site-packages/aiohttp", "aiohttp"),
    ("./env_timeflux_coherence_circle/lib/python3.9/site-packages/multidict", "multidict"),
    ("./env_timeflux_coherence_circle/lib/python3.9/site-packages/timeflux_dsp", "timeflux_dsp"),
    ("./env_timeflux_coherence_circle/lib/python3.9/site-packages/scipy", "scipy"),
    ("./env_timeflux_coherence_circle/lib/python3.9/site-packages/gephistreamer", "gephistreamer"),
    ("./env_timeflux_coherence_circle/lib/python3.9/site-packages/uinput", "uinput"),
    ("./env_timeflux_coherence_circle/lib/python3.9/site-packages/yarl", "yarl"),
    ("./env_timeflux_coherence_circle/lib/python3.9/site-packages/ws4py", "ws4py"),
    ("./env_timeflux_coherence_circle/lib/python3.9/site-packages/async_timeout", "async_timeout"),
    ("./env_timeflux_coherence_circle/lib/python3.9/site-packages/aiosignal", "aiosignal"),
    ("./env_timeflux_coherence_circle/lib/python3.9/site-packages/frozenlist", "frozenlist"),
    ("./env_timeflux_coherence_circle/lib/python3.9/site-packages/mne_connectivity", "mne_connectivity"),
    ("/usr/lib/python3.9/timeit.py", "timeit"),
    ("./env_timeflux_coherence_circle/lib/python3.9/site-packages/tqdm", "tqdm"),
    ("./env_timeflux_coherence_circle/lib/python3.9/site-packages/pyformulas", "pyformulas"),
    ("./env_timeflux_coherence_circle/lib/python3.9/site-packages/cv2", "cv2"),
    ("./env_timeflux_coherence_circle/lib/python3.9/site-packages/PIL", "PIL"),
    ],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='timeflux_coherence_circle',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='timeflux_coherence_circle',
)
